# Generated by Django 2.1.dev20171002151526 on 2017-10-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skip_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='origin_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_page', to='skip_logic.Page'),
        ),
    ]
