# Generated by Django 2.1.dev20171002151526 on 2017-10-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip_logic', '0002_path_origin_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.CharField(default=1, max_length=8),
        ),
    ]
