# Generated by Django 2.1.dev20171002151526 on 2017-10-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip_logic', '0003_auto_20171017_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_number',
            field=models.CharField(default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.CharField(default=1, max_length=8),
        ),
    ]
