# Generated by Django 2.1.dev20171002151526 on 2017-10-18 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skip_logic', '0004_auto_20171017_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path_choice', to='skip_logic.Choice'),
        ),
    ]
